-- =====================================================================
--  GenbaGo — demo seed  (DDS-14 §9; TEST-14 TC-005)
--  Reproduces SRS-14 Appendix A and AC-02…AC-09 through the real functions and triggers. Generated by seed14.py,
--  which also re-derives every expected value with the Python twins; PostgreSQL itself was not executed on the
--  authoring machine (README-14 "Verification"). The 16 probes at the end must each FAIL inside their transaction.
--
--  J1  Appendix A JA→TH (and J1E JA→EN): TM miss → glossary-constrained MT → clean checks → interpretation
--      injection_molding / problem_report, confidence 0.91, 5 curated checks, 4 indexed documents (AC-04, AC-08, AC-09)
--  J2  the same input after J1's approval → exact TM reuse, no model call (AC-07)
--  J3  8D report TH→JA, 12 segments: ±0.05 mm / 3.2 mm / LOT-2609-114 preserved (AC-02); 3.2 → 3.5 blocked;
--      修正措置 flagged as forbidden (AC-03); an omitted sentence flagged; a fuzzy TM candidate; edits with distances;
--      11 approved → TM; #12 left needs_review
--  J4  photo of a vertical 検査基準書: OCR regions, one handwritten note low-confidence, side-by-side result (AC-06)
--  J5  不良品は現場で処理してください → three readings, confidence 0.55 (AC-05)
--  J6  batch of 5 files, one failed and resumed (FR-20, NFR-07)   J7  HMI screenshot with layout kept (FR-19)
--  JD  a non-confidential Discord /jp request (IF-08)   + a 40-segment versioned test set with three evaluation runs
-- =====================================================================
SET TIME ZONE 'Asia/Bangkok';
BEGIN;

-- ---------------------------------------------------------------------
-- 1. Settings, users, roles
-- ---------------------------------------------------------------------
INSERT INTO genba.setting (key, value_num, value_text, description) VALUES
 ('tm_fuzzy_threshold',     0.85, NULL, 'FR-03: fuzzy matches >= 85 % are offered with a diff'),
 ('ambiguity_threshold',    0.60, NULL, 'FR-15: below this confidence the system lists readings instead of asserting'),
 ('max_readings',           3,    NULL, 'FR-15'),
 ('gate_glossary_min',      0.98, NULL, 'AI-02'),
 ('gate_numbers_min',       1,    NULL, 'AI-02'),
 ('gate_ped_max',           0.20, NULL, 'AI-02: normalised post-edit distance, JA→TH'),
 ('gate_class_min',         0.90, NULL, 'AI-05'),
 ('regression_pct',         2,    NULL, 'AI-08'),
 ('ocr_char_accuracy_min',  0.95, NULL, 'AI-06'),
 ('llm_max_params_b',       9,    NULL, 'AI-01 / §2.3'),
 ('llm_temperature',        0.3,  NULL, 'AI-01'),
 ('confidential_default',   1,    NULL, 'C-03'),
 ('retention_days',         365,  NULL, 'NFR-05'),
 ('model_name',             NULL, 'qwen2.5:7b-instruct-q4_K_M', 'a JA-capable local model <= 9 B'),
 ('ui_langs',               NULL, 'th,ja,en', 'NFR-06');

INSERT INTO core.app_user (id, username, display_name, role, lang) VALUES
 ('d0000000-0000-4000-8000-000000000001', 'nok', 'Nok Suwan (translator)', 'engineer', 'th'),
 ('d0000000-0000-4000-8000-000000000002', 'pranee', 'Pranee Srisuk (reviewer, QE)', 'engineer', 'th'),
 ('d0000000-0000-4000-8000-000000000003', 'admin', 'GenbaGo admin (terminology coordinator)', 'admin', 'en'),
 ('d0000000-0000-4000-8000-000000000004', 'sato', 'Sato Kenji (Japanese manager)', 'manager', 'ja'),
 ('d0000000-0000-4000-8000-000000000005', 'somchai', 'Somchai Jaidee (Thai engineer)', 'engineer', 'th');
INSERT INTO genba.user_role (user_id, role, granted_by, granted_at) VALUES
 ('d0000000-0000-4000-8000-000000000001', 'translator', 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('d0000000-0000-4000-8000-000000000002', 'reviewer', 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('d0000000-0000-4000-8000-000000000003', 'admin', 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00');

-- ---------------------------------------------------------------------
-- 2. Glossary (FR-21, NFR-08 — every insert creates version 1), aliases (FR-22), units, ratio bounds, keywords, check items, entity patterns
-- ---------------------------------------------------------------------
SELECT set_config('genba.effective_from', '2026-09-01', true);
SELECT set_config('genba.change_note', 'initial glossary seeded from existing bilingual documents', true);
INSERT INTO knowledge.glossary_term (id, ja, ja_reading, th, en, domain, notes, forbidden_json, approved_by, updated_at) VALUES
 ('e0000000-0000-4000-8000-000000000001', '成形条件', 'せいけいじょうけん', 'เงื่อนไขการขึ้นรูป', 'molding conditions', 'parameter', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000002', '不良率', 'ふりょうりつ', 'อัตราของเสีย', 'defect rate', 'metric', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000003', '保圧', 'ほあつ', 'แรงดันย้ำ', 'holding pressure', 'parameter', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000004', '金型', 'かながた', 'แม่พิมพ์', 'mould', 'general', NULL, '[{"lang": "en", "text": "mold die"}]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000005', '射出圧力', 'しゃしゅつあつりょく', 'แรงดันฉีด', 'injection pressure', 'parameter', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000006', '溶融温度', 'ようゆうおんど', 'อุณหภูมิหลอม', 'melt temperature', 'parameter', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000007', '冷却時間', 'れいきゃくじかん', 'เวลาหล่อเย็น', 'cooling time', 'parameter', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000008', 'サイクルタイム', 'さいくるたいむ', 'รอบเวลาการผลิต', 'cycle time', 'parameter', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000009', '是正処置', 'ぜせいしょち', 'มาตรการแก้ไข', 'corrective action', 'action', NULL, '[{"lang": "ja", "text": "修正措置"}, {"lang": "en", "text": "correction measure"}]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000010', '水平展開', 'すいへいてんかい', 'การขยายผลแนวราบ', 'horizontal deployment', 'action', NULL, '[{"lang": "ja", "text": "横展開"}]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000011', '作業標準書', 'さぎょうひょうじゅんしょ', 'เอกสารมาตรฐานการทำงาน', 'work standard', 'document', NULL, '[{"lang": "th", "text": "คู่มือการทำงาน"}]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000012', '検査基準書', 'けんさきじゅんしょ', 'เอกสารมาตรฐานการตรวจสอบ', 'inspection standard', 'document', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000013', '品質報告書', 'ひんしつほうこくしょ', 'รายงานคุณภาพ', 'quality report', 'document', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000014', '管理図', 'かんりず', 'แผนภูมิควบคุม', 'control chart', 'document', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000015', '公差', 'こうさ', 'พิกัดความคลาดเคลื่อน', 'tolerance', 'general', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000016', 'ロット', 'ろっと', 'ล็อต', 'lot', 'general', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000017', '再生材', 'さいせいざい', 'วัสดุรีไซเคิล', 'regrind', 'material', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000018', '乾燥', 'かんそう', 'การอบแห้ง', 'drying', 'process', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000019', '段取り', 'だんどり', 'การเตรียมงาน', 'changeover', 'process', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000020', 'チョコ停', 'ちょこてい', 'หยุดสั้น', 'micro-stop', 'metric', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000021', 'キズ', 'きず', 'รอยขีดข่วน', 'scratch', 'defect', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000022', 'バリ', 'ばり', 'ครีบ', 'burr', 'defect', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000023', 'ショート', 'しょーと', 'ชิ้นงานไม่เต็ม', 'short shot', 'defect', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000024', 'ヒケ', 'ひけ', 'รอยยุบ', 'sink mark', 'defect', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000025', '寸法', 'すんぽう', 'ขนาด', 'dimension', 'general', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000026', '検査', 'けんさ', 'การตรวจสอบ', 'inspection', 'process', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000027', '工程', 'こうてい', 'กระบวนการ', 'process step', 'general', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000028', '対策', 'たいさく', 'มาตรการ', 'countermeasure', 'action', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000029', '現場', 'げんば', 'หน้างาน', 'genba (shop floor)', 'general', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00'),
 ('e0000000-0000-4000-8000-000000000030', '溶接', 'ようせつ', 'การเชื่อม', 'welding', 'process', NULL, '[]'::jsonb, 'd0000000-0000-4000-8000-000000000003', '2026-09-01 09:00');
SELECT set_config('genba.effective_from', '', true); SELECT set_config('genba.change_note', '', true);
INSERT INTO genba.term_alias (term_id, alias, lang, kind, note) VALUES
 ('e0000000-0000-4000-8000-000000000001', '成条', 'ja', 'jargon', NULL),
 ('e0000000-0000-4000-8000-000000000021', '傷', 'ja', 'variant', NULL),
 ('e0000000-0000-4000-8000-000000000009', 'CA', 'en', 'abbreviation', NULL),
 ('e0000000-0000-4000-8000-000000000014', 'SPC chart', 'en', 'variant', NULL),
 ('e0000000-0000-4000-8000-000000000001', 'สภาพการฉีด', 'th', 'variant', NULL);
INSERT INTO genba.unit_alias (alias, canonical) VALUES
 ('มม.', 'mm'),
 ('มม', 'mm'),
 ('ミリメートル', 'mm'),
 ('ミリ', 'mm'),
 ('℃', '°C'),
 ('องศาเซลเซียส', '°C'),
 ('+/-', '±'),
 ('กก.', 'kg'),
 ('キロ', 'kg'),
 ('ชิ้น', 'pcs'),
 ('個', 'pcs');
INSERT INTO genba.ratio_bound (src_lang, tgt_lang, ratio_min, ratio_max) VALUES
 ('ja', 'th', 1.0, 3.5),
 ('ja', 'en', 1.0, 4.0),
 ('th', 'ja', 0.25, 1.0),
 ('th', 'en', 0.4, 1.5),
 ('en', 'ja', 0.4, 1.5),
 ('en', 'th', 0.6, 2.0);
INSERT INTO genba.process_keyword (process, lang, keyword, weight) VALUES
 ('injection_molding', 'ja', '成形', 1.0),
 ('injection_molding', 'ja', '成形条件', 1.5),
 ('injection_molding', 'ja', '射出', 1.0),
 ('injection_molding', 'ja', '金型', 0.8),
 ('injection_molding', 'th', 'ขึ้นรูป', 1.0),
 ('injection_molding', 'en', 'molding', 1.0),
 ('injection_molding', 'en', 'injection', 1.0),
 ('press', 'ja', 'プレス', 1.5),
 ('press', 'th', 'ปั๊ม', 1.0),
 ('press', 'en', 'press', 1.0),
 ('welding', 'ja', '溶接', 1.5),
 ('welding', 'th', 'เชื่อม', 1.0),
 ('welding', 'en', 'welding', 1.0),
 ('assembly', 'ja', '組立', 1.5),
 ('assembly', 'th', 'ประกอบ', 1.0),
 ('assembly', 'en', 'assembly', 1.0),
 ('painting', 'ja', '塗装', 1.5),
 ('painting', 'th', 'พ่นสี', 1.0),
 ('painting', 'en', 'painting', 1.0),
 ('inspection', 'ja', '検査', 1.0),
 ('inspection', 'ja', '検査基準書', 0.5),
 ('inspection', 'th', 'ตรวจสอบ', 1.0),
 ('inspection', 'en', 'inspection', 1.0),
 ('logistics', 'ja', '出荷', 1.5),
 ('logistics', 'ja', '物流', 1.0),
 ('logistics', 'th', 'จัดส่ง', 1.0),
 ('logistics', 'en', 'shipping', 1.0),
 ('maintenance', 'ja', '保全', 1.5),
 ('maintenance', 'ja', 'メンテナンス', 1.0),
 ('maintenance', 'th', 'ซ่อมบำรุง', 1.0),
 ('maintenance', 'en', 'maintenance', 1.0);
INSERT INTO genba.message_keyword (message_type, lang, keyword, weight) VALUES
 ('problem_report', 'ja', '不良率', 1.5),
 ('problem_report', 'ja', '上昇', 0.5),
 ('problem_report', 'ja', '発生', 1.0),
 ('problem_report', 'ja', '不具合', 1.5),
 ('problem_report', 'ja', '不良品', 0.5),
 ('problem_report', 'th', 'ของเสีย', 1.0),
 ('problem_report', 'th', 'เพิ่มขึ้น', 0.5),
 ('problem_report', 'en', 'defect', 1.0),
 ('problem_report', 'en', 'increased', 0.5),
 ('instruction', 'ja', 'ください', 1.0),
 ('instruction', 'ja', 'すること', 1.0),
 ('instruction', 'th', 'กรุณา', 1.0),
 ('instruction', 'en', 'please', 1.0),
 ('spec_change', 'ja', '変更', 0.4),
 ('spec_change', 'ja', '改訂', 1.5),
 ('spec_change', 'th', 'เปลี่ยนแปลงข้อกำหนด', 1.5),
 ('spec_change', 'en', 'revised', 1.0),
 ('audit_finding', 'ja', '監査', 1.5),
 ('audit_finding', 'ja', '指摘', 1.0),
 ('audit_finding', 'th', 'ตรวจประเมิน', 1.5),
 ('audit_finding', 'en', 'audit', 1.5),
 ('schedule', 'ja', '納期', 1.5),
 ('schedule', 'ja', '予定', 1.0),
 ('schedule', 'th', 'กำหนดการ', 1.5),
 ('schedule', 'en', 'schedule', 1.5),
 ('request', 'ja', '依頼', 1.5),
 ('request', 'ja', '処理', 0.5),
 ('request', 'ja', 'お願い', 1.0),
 ('request', 'th', 'ขอให้', 1.0),
 ('request', 'en', 'request', 1.5),
 ('information', 'ja', '連絡', 1.0),
 ('information', 'ja', 'お知らせ', 1.5),
 ('information', 'th', 'แจ้ง', 1.0),
 ('information', 'en', 'notice', 1.0);
INSERT INTO genba.check_item (id, process, message_type, ordinal, item_ja, item_en, item_th, moldmind_param) VALUES
 ('c0000000-0000-4000-8000-000000000001', 'injection_molding', 'problem_report', 1, '溶融温度・金型温度', 'Melt / mould temperature', 'อุณหภูมิหลอม・อุณหภูมิแม่พิมพ์', 'melt_temp,mould_temp'),
 ('c0000000-0000-4000-8000-000000000002', 'injection_molding', 'problem_report', 2, '射出圧力・速度', 'Injection pressure & speed', 'แรงดันฉีด・ความเร็วฉีด', 'inj_pressure,inj_speed'),
 ('c0000000-0000-4000-8000-000000000003', 'injection_molding', 'problem_report', 3, '保圧・保圧時間', 'Holding pressure & time', 'แรงดันย้ำ・เวลาย้ำ', 'hold_pressure,hold_time'),
 ('c0000000-0000-4000-8000-000000000004', 'injection_molding', 'problem_report', 4, '冷却時間・サイクルタイム', 'Cooling / cycle time', 'เวลาหล่อเย็น・รอบเวลาการผลิต', 'cooling_time,cycle_time'),
 ('c0000000-0000-4000-8000-000000000005', 'injection_molding', 'problem_report', 5, '材料ロット・乾燥・再生材比率', 'Material condition: lot, drying, regrind %', 'ล็อตวัสดุ・การอบแห้ง・สัดส่วนวัสดุรีไซเคิล', 'material_lot,drying,regrind_pct'),
 ('c0000000-0000-4000-8000-000000000006', 'injection_molding', 'spec_change', 1, '管理計画書の改訂', 'Control plan revision', 'การแก้ไขแผนควบคุม', NULL),
 ('c0000000-0000-4000-8000-000000000007', 'injection_molding', 'spec_change', 2, '初品検査', 'First-article inspection', 'การตรวจสอบชิ้นงานแรก', NULL),
 ('c0000000-0000-4000-8000-000000000008', 'press', 'problem_report', 1, '金型クリアランス', 'Die clearance', 'ระยะห่างแม่พิมพ์', NULL),
 ('c0000000-0000-4000-8000-000000000009', 'press', 'problem_report', 2, '材料板厚・ロット', 'Material thickness and lot', 'ความหนาวัสดุ・ล็อต', NULL),
 ('c0000000-0000-4000-8000-000000000010', 'press', 'problem_report', 3, 'プレス荷重・速度', 'Press tonnage and speed', 'แรงปั๊ม・ความเร็ว', NULL),
 ('c0000000-0000-4000-8000-000000000011', 'welding', 'problem_report', 1, '電流・電圧・送給速度', 'Current, voltage, wire feed', 'กระแส・แรงดัน・ความเร็วป้อนลวด', NULL),
 ('c0000000-0000-4000-8000-000000000012', 'welding', 'problem_report', 2, 'シールドガス流量', 'Shielding gas flow', 'อัตราการไหลของแก๊ส', NULL),
 ('c0000000-0000-4000-8000-000000000013', 'welding', 'problem_report', 3, '治具・位置決め', 'Fixture and positioning', 'จิ๊ก・การกำหนดตำแหน่ง', NULL);
INSERT INTO genba.entity_pattern (entity, pattern, canonical, ordinal) VALUES
 ('line', 'ライン\s*([0-9]+)', NULL, 1),
 ('line', 'Line\s*([0-9]+)', NULL, 2),
 ('line', 'ไลน์\s*([0-9]+)', NULL, 3),
 ('machine', '(M-[0-9]{2})', NULL, 1),
 ('mould', '(MD-[0-9]{3})', NULL, 1),
 ('part_number', '([A-Z]{2,4}-[0-9]{3}-[A-Z])', NULL, 1),
 ('lot', '(LOT-[0-9]{4}-[0-9]{3})', NULL, 1),
 ('quantity', '([0-9]+個)', NULL, 1),
 ('quantity', '([0-9]+ pcs)', NULL, 2),
 ('quantity', '([0-9]+ ชิ้น)', NULL, 3),
 ('date', '([0-9]{4}-[0-9]{2}-[0-9]{2})', NULL, 1),
 ('direction', '(上昇|増加|เพิ่มขึ้น|increase)', 'up', 1),
 ('direction', '(低下|減少|ลดลง|decrease)', 'down', 2);

-- ---------------------------------------------------------------------
-- 3. Indexed documents (knowledge.document) and their tags — the only source of related documents (AI-09)
-- ---------------------------------------------------------------------
INSERT INTO knowledge.document (id, sha256, kind, title, lang, uri, original_name, source_system, page_count, acl_json, ingested_at) VALUES
 ('a0000000-0000-4000-8000-000000000001', '217dbb48b7e865e52bbf91ee54e2c7a3f4a2f6db1531f387a88e578d30a4d678', 'control_plan', 'Control plan — RAD-500-A rev.7', 'ja', 's3://genbago-docs/index/001.pdf', 'Control plan — RAD-500-A rev.7.pdf', 'genba_memory', 4, '{"roles": ["engineer", "manager", "admin"]}', '2026-09-10 08:00'),
 ('a0000000-0000-4000-8000-000000000002', 'fcd295009781ebbf7b9e66bedfc5cc1d74a05220f233be6116f434b1f1514d86', 'fmea', 'FMEA — RAD-500-A, process step 20', 'ja', 's3://genbago-docs/index/002.pdf', 'FMEA — RAD-500-A, process step.pdf', 'genba_memory', 4, '{"roles": ["engineer", "manager", "admin"]}', '2026-09-10 08:00'),
 ('a0000000-0000-4000-8000-000000000003', '5f01abf41670e846cd20e06e7cc5adaf553000d3dff518a8da39fc7f4cd8d3ba', 'case', 'Past case #178 — mould polish overdue → scratch increase', 'th', 's3://genbago-docs/index/003.pdf', 'Past case #178 — mould polish .pdf', 'genba_memory', 4, '{"roles": ["engineer", "manager", "admin"]}', '2026-09-10 08:00'),
 ('a0000000-0000-4000-8000-000000000004', 'db26737a9a0d5eb4e9c8aa9d632c9b0046c224272442469e5ac01281edaa1001', 'spc', 'SPC chart — Line 3 fin pitch (last 30 days)', 'en', 's3://genbago-docs/index/004.pdf', 'SPC chart — Line 3 fin pitch (.pdf', 'genba_memory', 4, '{"roles": ["engineer", "manager", "admin"]}', '2026-09-10 08:00'),
 ('a0000000-0000-4000-8000-000000000005', '1fc8086c086379a12a189be3c194ff32bb7df956862de7156636672d02c8939c', 'work_standard', 'Work standard — press line 2 changeover', 'ja', 's3://genbago-docs/index/005.pdf', 'Work standard — press line 2 c.pdf', 'genba_memory', 4, '{"roles": ["engineer", "manager", "admin"]}', '2026-09-10 08:00');
INSERT INTO genba.document_tag (document_id, tag) VALUES
 ('a0000000-0000-4000-8000-000000000001', 'injection_molding'),
 ('a0000000-0000-4000-8000-000000000001', 'RAD-500-A'),
 ('a0000000-0000-4000-8000-000000000001', 'control_plan'),
 ('a0000000-0000-4000-8000-000000000002', 'injection_molding'),
 ('a0000000-0000-4000-8000-000000000002', 'RAD-500-A'),
 ('a0000000-0000-4000-8000-000000000002', 'fmea'),
 ('a0000000-0000-4000-8000-000000000003', 'injection_molding'),
 ('a0000000-0000-4000-8000-000000000003', 'キズ'),
 ('a0000000-0000-4000-8000-000000000003', 'mould'),
 ('a0000000-0000-4000-8000-000000000004', 'injection_molding'),
 ('a0000000-0000-4000-8000-000000000004', 'Line 3'),
 ('a0000000-0000-4000-8000-000000000004', 'RAD-500-A'),
 ('a0000000-0000-4000-8000-000000000004', 'spc'),
 ('a0000000-0000-4000-8000-000000000005', 'press'),
 ('a0000000-0000-4000-8000-000000000005', 'Line 2'),
 ('a0000000-0000-4000-8000-000000000005', '段取り');

-- ---------------------------------------------------------------------
-- 4. Translation memory bootstrap — 40 approved segments (approver = reviewer; trg_tm_index maintains the exact index)
-- ---------------------------------------------------------------------
INSERT INTO knowledge.tm_segment (id, src_lang, tgt_lang, src_text, tgt_text, domain, doc_ref, approver_id, created_at) VALUES
 ('b0000000-0000-4000-8000-000000000001', 'ja', 'th', '金型温度を上げてください。', 'กรุณาเพิ่มอุณหภูมิแม่พิมพ์', 'molding', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:00'),
 ('b0000000-0000-4000-8000-000000000002', 'ja', 'th', '不良率が上昇しています。', 'อัตราของเสียกำลังเพิ่มขึ้น', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:01'),
 ('b0000000-0000-4000-8000-000000000003', 'ja', 'th', '保圧を10%下げました。', 'ลดแรงดันย้ำลง 10% แล้ว', 'molding', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:02'),
 ('b0000000-0000-4000-8000-000000000004', 'ja', 'th', '検査基準書を改訂しました。', 'ได้แก้ไขเอกสารมาตรฐานการตรวจสอบแล้ว', 'document', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:03'),
 ('b0000000-0000-4000-8000-000000000005', 'ja', 'th', 'サイクルタイムは45 sです。', 'รอบเวลาการผลิตคือ 45 s', 'molding', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:04'),
 ('b0000000-0000-4000-8000-000000000006', 'ja', 'th', 'ロットLOT-2609-114を隔離してください。', 'กรุณากักล็อต LOT-2609-114', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:05'),
 ('b0000000-0000-4000-8000-000000000007', 'ja', 'th', '是正処置の期限は2026-09-30です。', 'กำหนดส่งมาตรการแก้ไขคือ 2026-09-30', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:06'),
 ('b0000000-0000-4000-8000-000000000008', 'ja', 'th', '水平展開を他ラインにも実施すること。', 'ให้ดำเนินการขยายผลแนวราบไปยังไลน์อื่นด้วย', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:07'),
 ('b0000000-0000-4000-8000-000000000009', 'ja', 'th', '再生材比率は20%以下にしてください。', 'กรุณาให้สัดส่วนวัสดุรีไซเคิลไม่เกิน 20%', 'material', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:08'),
 ('b0000000-0000-4000-8000-000000000010', 'ja', 'th', '乾燥時間は4 h以上です。', 'เวลาการอบแห้งคือ 4 h ขึ้นไป', 'material', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:09'),
 ('b0000000-0000-4000-8000-000000000011', 'ja', 'th', 'キズが3個発生しました。', 'พบรอยขีดข่วน 3 ชิ้น', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:10'),
 ('b0000000-0000-4000-8000-000000000012', 'ja', 'th', 'バリの原因は金型の摩耗です。', 'สาเหตุของครีบคือแม่พิมพ์สึกหรอ', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:11'),
 ('b0000000-0000-4000-8000-000000000013', 'ja', 'th', 'ショートは射出圧力不足で発生します。', 'ชิ้นงานไม่เต็มเกิดจากแรงดันฉีดไม่พอ', 'molding', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:12'),
 ('b0000000-0000-4000-8000-000000000014', 'ja', 'th', 'ヒケは冷却時間を延ばすと改善します。', 'รอยยุบจะดีขึ้นเมื่อยืดเวลาหล่อเย็น', 'molding', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:13'),
 ('b0000000-0000-4000-8000-000000000015', 'ja', 'th', '寸法公差は±0.05 mmです。', 'พิกัดความคลาดเคลื่อนของขนาดคือ ±0.05 mm', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:14'),
 ('b0000000-0000-4000-8000-000000000016', 'ja', 'th', '段取りは30 min以内で完了すること。', 'การเตรียมงานต้องเสร็จภายใน 30 min', 'production', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:15'),
 ('b0000000-0000-4000-8000-000000000017', 'ja', 'th', 'チョコ停が増加しています。', 'หยุดสั้นเพิ่มขึ้น', 'production', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:16'),
 ('b0000000-0000-4000-8000-000000000018', 'ja', 'th', '作業標準書に従ってください。', 'กรุณาปฏิบัติตามเอกสารมาตรฐานการทำงาน', 'document', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:17'),
 ('b0000000-0000-4000-8000-000000000019', 'ja', 'th', '管理図に異常点があります。', 'มีจุดผิดปกติในแผนภูมิควบคุม', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:18'),
 ('b0000000-0000-4000-8000-000000000020', 'ja', 'th', '溶接部にピンホールが発生しました。', 'พบรูพรุนที่จุดการเชื่อม', 'welding', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:19'),
 ('b0000000-0000-4000-8000-000000000021', 'ja', 'th', '対策を2026-10-05までに報告してください。', 'กรุณารายงานมาตรการภายใน 2026-10-05', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:20'),
 ('b0000000-0000-4000-8000-000000000022', 'ja', 'th', '現場で確認しました。', 'ยืนยันที่หน้างานแล้ว', 'general', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:21'),
 ('b0000000-0000-4000-8000-000000000023', 'ja', 'th', '工程20で検査を追加します。', 'จะเพิ่มการตรวจสอบที่กระบวนการ 20', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:22'),
 ('b0000000-0000-4000-8000-000000000024', 'ja', 'th', '溶融温度を230°Cに設定してください。', 'กรุณาตั้งอุณหภูมิหลอมที่ 230°C', 'molding', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:23'),
 ('b0000000-0000-4000-8000-000000000025', 'ja', 'th', '品質報告書を月曜日に提出します。', 'จะส่งรายงานคุณภาพในวันจันทร์', 'document', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:24'),
 ('b0000000-0000-4000-8000-000000000026', 'ja', 'en', '成形条件を確認してください。', 'Please check the molding conditions.', 'molding', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:25'),
 ('b0000000-0000-4000-8000-000000000027', 'ja', 'en', '不良率は5.82%です。', 'The defect rate is 5.82%.', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:26'),
 ('b0000000-0000-4000-8000-000000000028', 'ja', 'en', '是正処置を提出してください。', 'Please submit the corrective action.', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:27'),
 ('b0000000-0000-4000-8000-000000000029', 'ja', 'en', '金型を交換しました。', 'The mould was replaced.', 'molding', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:28'),
 ('b0000000-0000-4000-8000-000000000030', 'ja', 'en', '公差は±0.05 mmです。', 'The tolerance is ±0.05 mm.', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:29'),
 ('b0000000-0000-4000-8000-000000000031', 'ja', 'en', 'ロットLOT-2609-114は保留です。', 'Lot LOT-2609-114 is on hold.', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:30'),
 ('b0000000-0000-4000-8000-000000000032', 'ja', 'en', '水平展開を実施しました。', 'Horizontal deployment was carried out.', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:31'),
 ('b0000000-0000-4000-8000-000000000033', 'ja', 'en', '検査基準書を参照してください。', 'Please refer to the inspection standard.', 'document', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:32'),
 ('b0000000-0000-4000-8000-000000000034', 'ja', 'en', 'キズが増加しています。', 'Scratches are increasing.', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:33'),
 ('b0000000-0000-4000-8000-000000000035', 'ja', 'en', 'チョコ停が3回発生しました。', 'Micro-stops occurred 3 times.', 'production', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:34'),
 ('b0000000-0000-4000-8000-000000000036', 'th', 'ja', 'อัตราของเสียเพิ่มขึ้นหลังจากเปลี่ยนเงื่อนไขการขึ้นรูปเมื่อวานนี้', '昨日成形条件を変更した後、不良率が上昇しました。', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:35'),
 ('b0000000-0000-4000-8000-000000000037', 'th', 'ja', 'กรุณาส่งมาตรการแก้ไขภายในสัปดาห์นี้', '今週中に是正処置を提出してください。', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:36'),
 ('b0000000-0000-4000-8000-000000000038', 'th', 'ja', 'พบรอยขีดข่วนบนชิ้นงาน', 'ワークにキズが見つかりました。', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:37'),
 ('b0000000-0000-4000-8000-000000000039', 'th', 'ja', 'แม่พิมพ์ต้องขัดทุก 50000 ชิ้น', '金型は50000個ごとに研磨すること。', 'molding', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:38'),
 ('b0000000-0000-4000-8000-000000000040', 'th', 'ja', 'พิกัดความคลาดเคลื่อน ±0.05 mm', '公差 ±0.05 mm', 'quality', 'tmx:bootstrap-2026-09', 'd0000000-0000-4000-8000-000000000002', '2026-09-15 10:39');

-- ---------------------------------------------------------------------
-- 5. Jobs
-- ---------------------------------------------------------------------

-- J1
INSERT INTO genba.translation_job (id, kind, src_lang, tgt_lang, register, status, confidential, provider, channel, format, keep_layout, file_uri, result_uri, created_by, created_at) VALUES ('f0000000-0000-4000-8000-000000000001', 'text', 'ja', 'th', 'report', 'running', true, 'local', 'web', 'text', true, NULL, NULL, 'd0000000-0000-4000-8000-000000000005', '2026-09-22 09:00');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000001', 1, '成形条件を変更した後、不良率が上昇しました。', 'หลังจากเปลี่ยนเงื่อนไขการขึ้นรูป อัตราของเสียเพิ่มขึ้น', NULL);
SELECT genba.interpret((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000001' AND ordinal = 1), 'rules+qwen2.5:7b', 'interpret.v1');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000001' AND ordinal = 1), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 09:20');
UPDATE genba.translation_job SET status = 'done', finished_at = '2026-09-22 09:00'::timestamptz + interval '2 minutes' WHERE id = 'f0000000-0000-4000-8000-000000000001';

-- J1E
INSERT INTO genba.translation_job (id, kind, src_lang, tgt_lang, register, status, confidential, provider, channel, format, keep_layout, file_uri, result_uri, created_by, created_at) VALUES ('f0000000-0000-4000-8000-000000000002', 'text', 'ja', 'en', 'report', 'running', true, 'local', 'web', 'text', true, NULL, NULL, 'd0000000-0000-4000-8000-000000000004', '2026-09-22 09:05');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000002', 1, '成形条件を変更した後、不良率が上昇しました。', 'After changing the molding conditions, the defect rate increased.', NULL);
SELECT genba.interpret((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000002' AND ordinal = 1), 'rules+qwen2.5:7b', 'interpret.v1');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000002' AND ordinal = 1), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 09:22');
UPDATE genba.translation_job SET status = 'done', finished_at = '2026-09-22 09:05'::timestamptz + interval '2 minutes' WHERE id = 'f0000000-0000-4000-8000-000000000002';

-- J2
INSERT INTO genba.translation_job (id, kind, src_lang, tgt_lang, register, status, confidential, provider, channel, format, keep_layout, file_uri, result_uri, created_by, created_at) VALUES ('f0000000-0000-4000-8000-000000000003', 'text', 'ja', 'th', 'report', 'running', true, 'local', 'web', 'text', true, NULL, NULL, 'd0000000-0000-4000-8000-000000000001', '2026-09-22 09:30');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000003', 1, '成形条件を変更した後、不良率が上昇しました。', NULL, NULL);
UPDATE genba.translation_job SET status = 'done', finished_at = '2026-09-22 09:30'::timestamptz + interval '2 minutes' WHERE id = 'f0000000-0000-4000-8000-000000000003';

-- J3
INSERT INTO genba.translation_job (id, kind, src_lang, tgt_lang, register, status, confidential, provider, channel, format, keep_layout, file_uri, result_uri, created_by, created_at) VALUES ('f0000000-0000-4000-8000-000000000004', 'document', 'th', 'ja', 'customer', 'running', true, 'local', 'web', 'docx', true, 's3://genbago-docs/8d-rad500a-lot114.docx', 's3://genbago-results/8d-rad500a-lot114.ja.docx', 'd0000000-0000-4000-8000-000000000002', '2026-09-22 10:00');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 1, 'รายงาน 8D: ปัญหารอยขีดข่วนบนชิ้นงาน RAD-500-A ล็อต LOT-2609-114', '8Dレポート: RAD-500-A ロット LOT-2609-114 のキズ問題', 'p1');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 2, 'ค่าพิกัดความคลาดเคลื่อน ±0.05 mm ความหนา 3.2 mm ล็อต LOT-2609-114', '公差 ±0.05 mm、厚さ 3.2 mm、ロット LOT-2609-114', 'p2');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 3, 'ค่าที่วัดได้ 3.2 mm เกินพิกัดความคลาดเคลื่อน', '測定値 3.5 mm が公差を超過', 'p3');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 4, 'มาตรการแก้ไข: เปลี่ยนแม่พิมพ์และตรวจสอบซ้ำ', '修正措置: 金型を交換し再検査する', 'p4');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 5, 'สาเหตุคือแม่พิมพ์สึกหรอ  ได้ทำการขัดแม่พิมพ์แล้ว', '原因は金型の摩耗です。', 'p5');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 6, 'อัตราของเสียเพิ่มขึ้นหลังจากเปลี่ยนเงื่อนไขการขึ้นรูปเมื่อวาน', '昨日成形条件を変更した後、不良率が上昇しました。', 'p6');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 7, 'การขยายผลแนวราบไปยังไลน์ 1 และไลน์ 2', 'ライン1およびライン2への水平展開', 'p7');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 8, 'ตรวจสอบชิ้นงานแรก 50 ชิ้นหลังเปลี่ยนแม่พิมพ์', '金型交換後、初品50個を検査する', 'p8');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 9, 'ผลการตรวจสอบ: ไม่พบรอยขีดข่วน', '検査結果: キズなし', 'p9');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 10, 'อัตราของเสียลดลงเหลือ 0.4%', '不良率は0.4%まで低下', 'p10');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 11, 'ปิดรายงาน 8D วันที่ 2026-09-25', '8Dレポートを2026-09-25に完了', 'p11');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000004', 12, 'ผู้รับผิดชอบ: QE ไลน์ 3', '担当: QE ライン3', 'p12');
SELECT genba.interpret((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 1), 'rules+qwen2.5:7b', 'interpret.v1');
SELECT genba.interpret((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 4), 'rules+qwen2.5:7b', 'interpret.v1');
SELECT genba.edit_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 3), 'd0000000-0000-4000-8000-000000000001', '測定値 3.2 mm が公差を超過', '2026-09-22 10:30');
SELECT genba.edit_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 4), 'd0000000-0000-4000-8000-000000000001', '是正処置: 金型を交換し再検査する', '2026-09-22 10:32');
SELECT genba.edit_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 5), 'd0000000-0000-4000-8000-000000000001', '原因は金型の摩耗です。金型の研磨を実施済みです。', '2026-09-22 10:35');
UPDATE genba.segment SET status = 'needs_review' WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 12;
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 1), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 11:01');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 2), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 11:02');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 3), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 11:03');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 4), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 11:04');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 5), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 11:05');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 6), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 11:06');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 7), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 11:07');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 8), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 11:08');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 9), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 11:09');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 10), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 11:10');
SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 11), 'd0000000-0000-4000-8000-000000000002', NULL, '2026-09-22 11:11');
UPDATE genba.translation_job SET status = 'done', finished_at = '2026-09-22 10:00'::timestamptz + interval '2 minutes' WHERE id = 'f0000000-0000-4000-8000-000000000004';

-- J4
INSERT INTO genba.translation_job (id, kind, src_lang, tgt_lang, register, status, confidential, provider, channel, format, keep_layout, file_uri, result_uri, created_by, created_at) VALUES ('f0000000-0000-4000-8000-000000000005', 'ocr', 'ja', 'th', 'report', 'running', true, 'local', 'web', 'image', true, 's3://genbago-docs/kensa-kijun-photo.jpg', 's3://genbago-results/kensa-kijun-side-by-side.pdf', 'd0000000-0000-4000-8000-000000000005', '2026-09-22 13:00');
INSERT INTO genba.ocr_page (id, job_id, page_no, image_uri, width_px, height_px, layout_mode) VALUES ('f1000000-0000-4000-8000-000000000005', 'f0000000-0000-4000-8000-000000000005', 1, 's3://genbago-docs/kensa-kijun-photo.jpg', 2480, 3508, 'side_by_side');
INSERT INTO genba.ocr_region (page_id, ordinal, bbox_json, orientation, text, char_confidence, handwriting) VALUES
 ('f1000000-0000-4000-8000-000000000005', 1, '{"x": 2200, "y": 120, "w": 120, "h": 1400}'::jsonb, 'vertical', '検査基準書 RAD-500-A', 0.981, false),
 ('f1000000-0000-4000-8000-000000000005', 2, '{"x": 2000, "y": 120, "w": 120, "h": 2600}'::jsonb, 'vertical', '外観検査: キズ、バリ、ヒケがないこと。', 0.972, false),
 ('f1000000-0000-4000-8000-000000000005', 3, '{"x": 1800, "y": 120, "w": 120, "h": 2600}'::jsonb, 'vertical', '寸法検査: 厚さ 3.2 mm ±0.05 mm を測定すること。', 0.966, false),
 ('f1000000-0000-4000-8000-000000000005', 4, '{"x": 300, "y": 2900, "w": 1400, "h": 300}'::jsonb, 'horizontal', '9/20 金型研磨済み', 0.712, true);
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000005', 1, '検査基準書 RAD-500-A', 'เอกสารมาตรฐานการตรวจสอบ RAD-500-A', 'region:1');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000005', 2, '外観検査: キズ、バリ、ヒケがないこと。', 'การตรวจสอบภายนอก: ต้องไม่มีรอยขีดข่วน ครีบ รอยยุบ', 'region:2');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000005', 3, '寸法検査: 厚さ 3.2 mm ±0.05 mm を測定すること。', 'การตรวจสอบขนาด: วัดความหนา 3.2 mm ±0.05 mm', 'region:3');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000005', 4, '9/20 金型研磨済み', '9/20 ขัดแม่พิมพ์แล้ว', 'region:4');
UPDATE genba.ocr_region r SET segment_id = s.id FROM genba.segment s, genba.ocr_page p WHERE p.id = r.page_id AND p.job_id = 'f0000000-0000-4000-8000-000000000005' AND s.job_id = p.job_id AND s.anchor = 'region:' || r.ordinal;
UPDATE genba.translation_job SET status = 'done', finished_at = '2026-09-22 13:00'::timestamptz + interval '2 minutes' WHERE id = 'f0000000-0000-4000-8000-000000000005';

-- J5
INSERT INTO genba.translation_job (id, kind, src_lang, tgt_lang, register, status, confidential, provider, channel, format, keep_layout, file_uri, result_uri, created_by, created_at) VALUES ('f0000000-0000-4000-8000-000000000006', 'text', 'ja', 'th', 'shopfloor', 'running', true, 'local', 'web', 'text', true, NULL, NULL, 'd0000000-0000-4000-8000-000000000005', '2026-09-22 14:00');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000006', 1, '不良品は現場で処理してください', 'กรุณาจัดการของเสียที่หน้างาน', NULL);
INSERT INTO genba.reading (segment_id, ordinal, reading_ja, th, en, usage_note) VALUES ((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000006' AND ordinal = 1), 1, '処理 = 廃棄する', 'ทิ้ง/ทำลายของเสียที่หน้างาน', 'dispose of the defective parts on the shop floor', 'common in 現場メモ when a scrap bin is at the line');
INSERT INTO genba.reading (segment_id, ordinal, reading_ja, th, en, usage_note) VALUES ((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000006' AND ordinal = 1), 2, '処理 = 手直しする', 'แก้ไข/ซ่อมของเสียที่หน้างาน', 'rework the defective parts on the shop floor', 'when a rework station exists at the line');
INSERT INTO genba.reading (segment_id, ordinal, reading_ja, th, en, usage_note) VALUES ((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000006' AND ordinal = 1), 3, '処理 = 対応・記録する', 'จัดการ/บันทึกของเสียที่หน้างาน', 'handle (sort and record) the defective parts on the shop floor', 'the safe reading; confirm with the sender');
SELECT genba.interpret((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000006' AND ordinal = 1), 'rules+qwen2.5:7b', 'interpret.v1');
UPDATE genba.translation_job SET status = 'done', finished_at = '2026-09-22 14:00'::timestamptz + interval '2 minutes' WHERE id = 'f0000000-0000-4000-8000-000000000006';

-- J6
INSERT INTO genba.translation_job (id, kind, src_lang, tgt_lang, register, status, confidential, provider, channel, format, keep_layout, file_uri, result_uri, created_by, created_at) VALUES ('f0000000-0000-4000-8000-000000000007', 'batch', 'ja', 'th', 'report', 'running', true, 'local', 'batch', 'docx', true, 's3://genbago-docs/batch-2026-09-22/', 's3://genbago-results/batch-2026-09-22/', 'd0000000-0000-4000-8000-000000000001', '2026-09-22 15:00');
INSERT INTO genba.job_file (job_id, ordinal, name, uri, format, status, segment_count, error) VALUES
 ('f0000000-0000-4000-8000-000000000007', 1, 'sagyou-hyoujun-01.docx', 's3://genbago-docs/batch-2026-09-22/sagyou-hyoujun-01.docx', 'docx', 'done', 6, NULL),
 ('f0000000-0000-4000-8000-000000000007', 2, 'sagyou-hyoujun-02.docx', 's3://genbago-docs/batch-2026-09-22/sagyou-hyoujun-02.docx', 'docx', 'done', 5, NULL),
 ('f0000000-0000-4000-8000-000000000007', 3, 'kensa-kijun-03.xlsx', 's3://genbago-docs/batch-2026-09-22/kensa-kijun-03.xlsx', 'xlsx', 'done', 4, NULL),
 ('f0000000-0000-4000-8000-000000000007', 4, 'kensa-kijun-04.xlsx', 's3://genbago-docs/batch-2026-09-22/kensa-kijun-04.xlsx', 'xlsx', 'failed', 0, 'corrupt XLSX: shared strings table missing'),
 ('f0000000-0000-4000-8000-000000000007', 5, 'hinshitsu-houkoku-05.pptx', 's3://genbago-docs/batch-2026-09-22/hinshitsu-houkoku-05.pptx', 'pptx', 'queued', 0, NULL);
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000007', 1, '作業標準書に従ってください。', 'กรุณาปฏิบัติตามเอกสารมาตรฐานการทำงาน', 'file:1#p1');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000007', 2, '段取りは30 min以内で完了すること。', 'การเตรียมงานต้องเสร็จภายใน 30 min', 'file:1#p2');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000007', 3, '金型温度を上げてください。', 'กรุณาเพิ่มอุณหภูมิแม่พิมพ์', 'file:2#p1');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000007', 4, '検査基準書を改訂しました。', 'ได้แก้ไขเอกสารมาตรฐานการตรวจสอบแล้ว', 'file:3#c1');
UPDATE genba.translation_job SET status = 'failed', error = 'file 4: corrupt XLSX: shared strings table missing', finished_at = '2026-09-22 15:00'::timestamptz + interval '4 minutes' WHERE id = 'f0000000-0000-4000-8000-000000000007';
SELECT genba.resume_job('f0000000-0000-4000-8000-000000000007');   -- NFR-07: resumes at file 4
UPDATE genba.job_file SET status = 'done', segment_count = 4, error = NULL WHERE job_id = 'f0000000-0000-4000-8000-000000000007' AND ordinal = 4;
UPDATE genba.job_file SET status = 'done', segment_count = 3, error = NULL WHERE job_id = 'f0000000-0000-4000-8000-000000000007' AND ordinal = 5;
UPDATE genba.translation_job SET status = 'done', finished_at = '2026-09-22 15:00'::timestamptz + interval '9 minutes' WHERE id = 'f0000000-0000-4000-8000-000000000007';

-- J7
INSERT INTO genba.translation_job (id, kind, src_lang, tgt_lang, register, status, confidential, provider, channel, format, keep_layout, file_uri, result_uri, created_by, created_at) VALUES ('f0000000-0000-4000-8000-000000000008', 'hmi', 'ja', 'en', 'shopfloor', 'running', true, 'local', 'web', 'image', true, 's3://genbago-docs/hmi-m07.png', 's3://genbago-results/hmi-m07.en.png', 'd0000000-0000-4000-8000-000000000005', '2026-09-22 16:00');
INSERT INTO genba.ocr_page (id, job_id, page_no, image_uri, width_px, height_px, layout_mode) VALUES ('f1000000-0000-4000-8000-000000000008', 'f0000000-0000-4000-8000-000000000008', 1, 's3://genbago-docs/hmi-m07.png', 1280, 800, 'keep_layout');
INSERT INTO genba.ocr_region (page_id, ordinal, bbox_json, orientation, text, char_confidence, handwriting) VALUES
 ('f1000000-0000-4000-8000-000000000008', 1, '{"x": 40, "y": 30, "w": 400, "h": 60}'::jsonb, 'horizontal', '射出圧力 85 MPa', 0.99, false),
 ('f1000000-0000-4000-8000-000000000008', 2, '{"x": 40, "y": 110, "w": 400, "h": 60}'::jsonb, 'horizontal', '保圧 45 MPa / 3 s', 0.985, false),
 ('f1000000-0000-4000-8000-000000000008', 3, '{"x": 40, "y": 190, "w": 400, "h": 60}'::jsonb, 'horizontal', '冷却時間 18 s', 0.99, false);
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000008', 1, '射出圧力 85 MPa', 'injection pressure 85 MPa', 'region:1');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000008', 2, '保圧 45 MPa / 3 s', 'holding pressure 45 MPa / 3 s', 'region:2');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000008', 3, '冷却時間 18 s', 'cooling time 18 s', 'region:3');
UPDATE genba.ocr_region r SET segment_id = s.id FROM genba.segment s, genba.ocr_page p WHERE p.id = r.page_id AND p.job_id = 'f0000000-0000-4000-8000-000000000008' AND s.job_id = p.job_id AND s.anchor = 'region:' || r.ordinal;
UPDATE genba.translation_job SET status = 'done', finished_at = '2026-09-22 16:00'::timestamptz + interval '2 minutes' WHERE id = 'f0000000-0000-4000-8000-000000000008';

-- JD
INSERT INTO genba.translation_job (id, kind, src_lang, tgt_lang, register, status, confidential, provider, channel, format, keep_layout, file_uri, result_uri, created_by, created_at) VALUES ('f0000000-0000-4000-8000-000000000009', 'text', 'ja', 'th', 'shopfloor', 'running', false, 'local', 'discord', 'text', true, NULL, NULL, 'd0000000-0000-4000-8000-000000000005', '2026-09-22 16:30');
SELECT genba.add_segment('f0000000-0000-4000-8000-000000000009', 1, 'ライン3のチョコ停が増加しています。', 'หยุดสั้นของไลน์ 3 เพิ่มขึ้น', NULL);
UPDATE genba.translation_job SET status = 'done', finished_at = '2026-09-22 16:30'::timestamptz + interval '2 minutes' WHERE id = 'f0000000-0000-4000-8000-000000000009';

-- FR-23 / FR-26: mined candidates from the approved 8D and daily usage
SELECT genba.mine_candidates('f0000000-0000-4000-8000-000000000004');
SELECT genba.rollup_term_usage('2026-09-22');
UPDATE genba.term_candidate SET status = 'accepted', decided_by = 'd0000000-0000-4000-8000-000000000003', decided_at = '2026-09-22 17:00' WHERE ja = (SELECT ja FROM genba.term_candidate ORDER BY occurrences DESC, ja LIMIT 1);

-- NFR-08: a glossary change → version 2 with approver and effective date
SELECT set_config('genba.effective_from', '2026-10-01', true); SELECT set_config('genba.change_note', 'Thai rendering aligned with the customer glossary', true);
UPDATE knowledge.glossary_term SET th = 'มาตรการแก้ไขและป้องกัน', approved_by = 'd0000000-0000-4000-8000-000000000003', updated_at = '2026-09-22 17:10' WHERE id = 'e0000000-0000-4000-8000-000000000009';
SELECT set_config('genba.effective_from', '', true); SELECT set_config('genba.change_note', '', true);

-- ---------------------------------------------------------------------
-- 6. Domain test set v1 (40 JA→TH segments, labelled) and three evaluation runs (AI-02, AI-03, AI-05, AI-08)
-- ---------------------------------------------------------------------
INSERT INTO genba.test_set (id, name, version, description, frozen, created_by, created_at) VALUES ('90000000-0000-4000-8000-000000000001', 'genba-domain-set', 1, 'Real-document sentences per process x message type (seed scale: 40; the plant set is >= 200 / >= 300, AI-02/AI-05)', true, 'd0000000-0000-4000-8000-000000000003', '2026-09-05 09:00');
INSERT INTO genba.test_segment (id, test_set_id, ordinal, src_lang, tgt_lang, src_text, reference_text, expected_process, expected_message_type, domain) VALUES
 ('91000000-0000-4000-8000-000000000001', '90000000-0000-4000-8000-000000000001', 1, 'ja', 'th', '成形条件を変更した後、不良率が上昇しました。', 'หลังจากเปลี่ยนเงื่อนไขการขึ้นรูป อัตราของเสียเพิ่มขึ้น', 'injection_molding', 'problem_report', 'injection_molding'),
 ('91000000-0000-4000-8000-000000000002', '90000000-0000-4000-8000-000000000001', 2, 'ja', 'th', '成形機の金型温度を確認してください。', 'กรุณาตรวจสอบอุณหภูมิแม่พิมพ์ของเครื่องขึ้นรูป', 'injection_molding', 'instruction', 'injection_molding'),
 ('91000000-0000-4000-8000-000000000003', '90000000-0000-4000-8000-000000000001', 3, 'ja', 'th', '成形の保圧条件を改訂しました。', 'ได้แก้ไขเงื่อนไขแรงดันย้ำของการขึ้นรูปแล้ว', 'injection_molding', 'spec_change', 'injection_molding'),
 ('91000000-0000-4000-8000-000000000004', '90000000-0000-4000-8000-000000000001', 4, 'ja', 'th', '射出成形ラインの段取り短縮を依頼します。', 'ขอให้ลดเวลาการเตรียมงานของไลน์ฉีดขึ้นรูป', 'injection_molding', 'request', 'injection_molding'),
 ('91000000-0000-4000-8000-000000000005', '90000000-0000-4000-8000-000000000001', 5, 'ja', 'th', '成形ラインの再生材比率をお知らせします。', 'แจ้งสัดส่วนวัสดุรีไซเคิลของไลน์ขึ้นรูป', 'injection_molding', 'information', 'injection_molding'),
 ('91000000-0000-4000-8000-000000000006', '90000000-0000-4000-8000-000000000001', 6, 'ja', 'th', 'プレス工程でバリが発生しました。', 'เกิดครีบในกระบวนการปั๊ม', 'press', 'problem_report', 'press'),
 ('91000000-0000-4000-8000-000000000007', '90000000-0000-4000-8000-000000000001', 7, 'ja', 'th', 'プレス金型のクリアランスを確認すること。', 'ให้ตรวจสอบระยะห่างแม่พิมพ์ปั๊ม', 'press', 'instruction', 'press'),
 ('91000000-0000-4000-8000-000000000008', '90000000-0000-4000-8000-000000000001', 8, 'ja', 'th', 'プレス工程の監査で指摘がありました。', 'มีข้อชี้แนะจากการตรวจประเมินกระบวนการปั๊ม', 'press', 'audit_finding', 'press'),
 ('91000000-0000-4000-8000-000000000009', '90000000-0000-4000-8000-000000000001', 9, 'ja', 'th', 'プレスラインの納期は2026-10-01です。', 'กำหนดส่งของไลน์ปั๊มคือ 2026-10-01', 'press', 'schedule', 'press'),
 ('91000000-0000-4000-8000-000000000010', '90000000-0000-4000-8000-000000000001', 10, 'ja', 'th', 'プレス機の点検結果をお知らせします。', 'แจ้งผลการตรวจเช็คเครื่องปั๊ม', 'press', 'information', 'press'),
 ('91000000-0000-4000-8000-000000000011', '90000000-0000-4000-8000-000000000001', 11, 'ja', 'th', '溶接部に不具合が発生しました。', 'เกิดข้อบกพร่องที่จุดการเชื่อม', 'welding', 'problem_report', 'welding'),
 ('91000000-0000-4000-8000-000000000012', '90000000-0000-4000-8000-000000000001', 12, 'ja', 'th', '溶接電流を確認してください。', 'กรุณาตรวจสอบกระแสการเชื่อม', 'welding', 'instruction', 'welding'),
 ('91000000-0000-4000-8000-000000000013', '90000000-0000-4000-8000-000000000001', 13, 'ja', 'th', '溶接条件を改訂しました。', 'ได้แก้ไขเงื่อนไขการเชื่อมแล้ว', 'welding', 'spec_change', 'welding'),
 ('91000000-0000-4000-8000-000000000014', '90000000-0000-4000-8000-000000000001', 14, 'ja', 'th', '溶接治具の修理を依頼します。', 'ขอให้ซ่อมจิ๊กการเชื่อม', 'welding', 'request', 'welding'),
 ('91000000-0000-4000-8000-000000000015', '90000000-0000-4000-8000-000000000001', 15, 'ja', 'th', '溶接ラインの立上げ予定は来週です。', 'กำหนดการเริ่มไลน์การเชื่อมคือสัปดาห์หน้า', 'welding', 'schedule', 'welding'),
 ('91000000-0000-4000-8000-000000000016', '90000000-0000-4000-8000-000000000001', 16, 'ja', 'th', '組立工程で不具合が発生しました。', 'เกิดข้อบกพร่องในกระบวนการประกอบ', 'assembly', 'problem_report', 'assembly'),
 ('91000000-0000-4000-8000-000000000017', '90000000-0000-4000-8000-000000000001', 17, 'ja', 'th', '組立手順は作業標準書に従ってください。', 'กรุณาทำตามขั้นตอนการประกอบตามเอกสารมาตรฐานการทำงาน', 'assembly', 'instruction', 'assembly'),
 ('91000000-0000-4000-8000-000000000018', '90000000-0000-4000-8000-000000000001', 18, 'ja', 'th', '組立工程の監査で指摘事項が3件ありました。', 'มีข้อชี้แนะ 3 รายการจากการตรวจประเมินกระบวนการประกอบ', 'assembly', 'audit_finding', 'assembly'),
 ('91000000-0000-4000-8000-000000000019', '90000000-0000-4000-8000-000000000001', 19, 'ja', 'th', '組立ラインの納期を確認しました。', 'ยืนยันกำหนดส่งของไลน์ประกอบแล้ว', 'assembly', 'schedule', 'assembly'),
 ('91000000-0000-4000-8000-000000000020', '90000000-0000-4000-8000-000000000001', 20, 'ja', 'th', '組立ラインの人員について。', 'เกี่ยวกับจำนวนพนักงานของไลน์ประกอบ', 'assembly', 'information', 'assembly'),
 ('91000000-0000-4000-8000-000000000021', '90000000-0000-4000-8000-000000000001', 21, 'ja', 'th', '塗装工程でキズが発生しました。', 'เกิดรอยขีดข่วนในกระบวนการพ่นสี', 'painting', 'problem_report', 'painting'),
 ('91000000-0000-4000-8000-000000000022', '90000000-0000-4000-8000-000000000001', 22, 'ja', 'th', '塗装ブースの温度を確認してください。', 'กรุณาตรวจสอบอุณหภูมิห้องพ่นสี', 'painting', 'instruction', 'painting'),
 ('91000000-0000-4000-8000-000000000023', '90000000-0000-4000-8000-000000000001', 23, 'ja', 'th', '塗装条件を改訂しました。', 'ได้แก้ไขเงื่อนไขการพ่นสีแล้ว', 'painting', 'spec_change', 'painting'),
 ('91000000-0000-4000-8000-000000000024', '90000000-0000-4000-8000-000000000001', 24, 'ja', 'th', '塗装治具の追加を依頼します。', 'ขอให้เพิ่มจิ๊กพ่นสี', 'painting', 'request', 'painting'),
 ('91000000-0000-4000-8000-000000000025', '90000000-0000-4000-8000-000000000001', 25, 'ja', 'th', '塗装ラインの予定を共有します。', 'แชร์กำหนดการของไลน์พ่นสี', 'painting', 'schedule', 'painting'),
 ('91000000-0000-4000-8000-000000000026', '90000000-0000-4000-8000-000000000001', 26, 'ja', 'th', '検査で不良品が10個発生しました。', 'พบของเสีย 10 ชิ้นจากการตรวจสอบ', 'inspection', 'problem_report', 'inspection'),
 ('91000000-0000-4000-8000-000000000027', '90000000-0000-4000-8000-000000000001', 27, 'ja', 'th', '検査基準書に従って検査してください。', 'กรุณาตรวจสอบตามเอกสารมาตรฐานการตรวจสอบ', 'inspection', 'instruction', 'inspection'),
 ('91000000-0000-4000-8000-000000000028', '90000000-0000-4000-8000-000000000001', 28, 'ja', 'th', '検査基準書を改訂しました。', 'ได้แก้ไขเอกสารมาตรฐานการตรวจสอบแล้ว', 'inspection', 'spec_change', 'inspection'),
 ('91000000-0000-4000-8000-000000000029', '90000000-0000-4000-8000-000000000001', 29, 'ja', 'th', '検査記録について監査で指摘されました。', 'มีข้อชี้แนะจากการตรวจประเมินเกี่ยวกับบันทึกการตรวจสอบ', 'inspection', 'audit_finding', 'inspection'),
 ('91000000-0000-4000-8000-000000000030', '90000000-0000-4000-8000-000000000001', 30, 'ja', 'th', '検査員の追加を依頼します。', 'ขอให้เพิ่มพนักงานฝ่ายการตรวจสอบ', 'inspection', 'request', 'inspection'),
 ('91000000-0000-4000-8000-000000000031', '90000000-0000-4000-8000-000000000001', 31, 'ja', 'th', '出荷で不具合が発生しました。', 'เกิดข้อบกพร่องในการจัดส่ง', 'logistics', 'problem_report', 'logistics'),
 ('91000000-0000-4000-8000-000000000032', '90000000-0000-4000-8000-000000000001', 32, 'ja', 'th', '出荷前にラベルを確認してください。', 'กรุณาตรวจสอบฉลากก่อนจัดส่ง', 'logistics', 'instruction', 'logistics'),
 ('91000000-0000-4000-8000-000000000033', '90000000-0000-4000-8000-000000000001', 33, 'ja', 'th', '出荷の納期は2026-09-30です。', 'กำหนดส่งของการจัดส่งคือ 2026-09-30', 'logistics', 'schedule', 'logistics'),
 ('91000000-0000-4000-8000-000000000034', '90000000-0000-4000-8000-000000000001', 34, 'ja', 'th', '物流の追加便を依頼します。', 'ขอให้เพิ่มเที่ยวรถขนส่ง', 'logistics', 'request', 'logistics'),
 ('91000000-0000-4000-8000-000000000035', '90000000-0000-4000-8000-000000000001', 35, 'ja', 'th', '出荷数量をお知らせします。', 'แจ้งจำนวนการจัดส่ง', 'logistics', 'information', 'logistics'),
 ('91000000-0000-4000-8000-000000000036', '90000000-0000-4000-8000-000000000001', 36, 'ja', 'th', '保全点検で不具合が発生しました。', 'พบข้อบกพร่องจากการตรวจเช็คซ่อมบำรุง', 'maintenance', 'problem_report', 'maintenance'),
 ('91000000-0000-4000-8000-000000000037', '90000000-0000-4000-8000-000000000001', 37, 'ja', 'th', 'メンテナンス後に動作確認をしてください。', 'กรุณาตรวจสอบการทำงานหลังซ่อมบำรุง', 'maintenance', 'instruction', 'maintenance'),
 ('91000000-0000-4000-8000-000000000038', '90000000-0000-4000-8000-000000000001', 38, 'ja', 'th', '保全の予定は毎月第一月曜日です。', 'กำหนดการซ่อมบำรุงคือวันจันทร์แรกของทุกเดือน', 'maintenance', 'schedule', 'maintenance'),
 ('91000000-0000-4000-8000-000000000039', '90000000-0000-4000-8000-000000000001', 39, 'ja', 'th', '保全の状況を連絡してください。', 'กรุณาแจ้งสถานะการซ่อมบำรุง', 'maintenance', 'information', 'maintenance'),
 ('91000000-0000-4000-8000-000000000040', '90000000-0000-4000-8000-000000000001', 40, 'ja', 'th', '出荷時間の調整は可能でしょうか。', 'สามารถปรับเวลาจัดส่งได้หรือไม่', 'logistics', 'request', 'logistics');
INSERT INTO genba.eval_run (id, test_set_id, run_at, model, prompt_version, note) VALUES ('92000000-0000-4000-8000-000000000001', '90000000-0000-4000-8000-000000000001', '2026-07-31 22:00', 'qwen2.5:7b-instruct-q4_K_M', 'translate.v1', 'baseline');
INSERT INTO genba.eval_result (eval_run_id, test_segment_id, mt_text, ped, glossary_ok, numbers_ok, process_pred, message_pred) VALUES
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000001', 'หลังจากเปลี่ยนเงื่อนไขการขึ้นรูป อัตราของเสียเพิ่มขึ้น', 0.0700, true, true, 'injection_molding', 'problem_report'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000002', 'กรุณาตรวจสอบอุณหภูมิแม่พิมพ์ของเครื่องขึ้นรูป', 0.1400, true, true, 'injection_molding', 'instruction'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000003', 'ได้แก้ไขเงื่อนไขแรงดันย้ำของการขึ้นรูปแล้ว', 0.2100, true, true, 'injection_molding', 'spec_change'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000004', 'ขอให้ลดเวลาการเตรียมงานของไลน์ฉีดขึ้นรูป', 0.2800, true, true, 'injection_molding', 'request'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000005', 'แจ้งสัดส่วนวัสดุรีไซเคิลของไลน์ขึ้นรูป', 0.0400, true, true, 'injection_molding', 'information'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000006', 'เกิดครีบในกระบวนการปั๊ม', 0.1100, true, true, 'press', 'problem_report'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000007', 'ให้ตรวจสอบระยะห่างแม่พิมพ์ปั๊ม', 0.1800, true, true, 'press', 'instruction'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000008', 'มีข้อชี้แนะจากการตรวจประเมินกระบวนการปั๊ม', 0.2500, true, true, 'press', 'audit_finding'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000009', 'กำหนดส่งของไลน์ปั๊มคือ 2026-10-01', 0.0100, true, true, 'press', 'schedule'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000010', 'แจ้งผลการตรวจเช็คเครื่องปั๊ม', 0.0800, true, true, 'press', 'information'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000011', 'เกิดข้อบกพร่องที่จุดการเชื่อม', 0.1500, true, true, 'welding', 'problem_report'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000012', 'กรุณาตรวจสอบกระแสการเชื่อม', 0.2200, true, true, 'welding', 'instruction'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000013', 'ได้แก้ไขเงื่อนไขการเชื่อมแล้ว', 0.2900, true, true, 'welding', 'spec_change'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000014', 'ขอให้ซ่อมจิ๊กการเชื่อม', 0.0500, true, true, 'welding', 'request'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000015', 'กำหนดการเริ่มไลน์การเชื่อมคือสัปดาห์หน้า', 0.1200, true, true, 'welding', 'schedule'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000016', 'เกิดข้อบกพร่องในกระบวนการประกอบ', 0.1900, true, true, 'assembly', 'problem_report'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000017', 'กรุณาทำตามขั้นตอนการประกอบตามเอกสารมาตรฐานการทำงาน', 0.2600, true, true, 'assembly', 'instruction'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000018', 'มีข้อชี้แนะ 3 รายการจากการตรวจประเมินกระบวนการประกอบ', 0.0200, true, true, 'assembly', 'audit_finding'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000019', 'ยืนยันกำหนดส่งของไลน์ประกอบแล้ว', 0.0900, true, true, 'assembly', 'schedule'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000020', 'เกี่ยวกับจำนวนพนักงานของไลน์ประกอบ', 0.1600, true, true, 'assembly', NULL),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000021', 'เกิดรอยขีดข่วนในกระบวนการพ่นสี', 0.2300, true, true, 'painting', 'problem_report'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000022', 'กรุณาตรวจสอบอุณหภูมิห้องพ่นสี', 0.3000, true, true, 'painting', 'instruction'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000023', 'ได้แก้ไขเงื่อนไขการพ่นสีแล้ว', 0.0600, true, true, 'painting', 'spec_change'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000024', 'ขอให้เพิ่มจิ๊กพ่นสี', 0.1300, true, true, 'painting', 'request'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000025', 'แชร์กำหนดการของไลน์พ่นสี', 0.2000, true, true, 'painting', 'schedule'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000026', 'พบของเสีย 10 ชิ้นจากการตรวจสอบ', 0.2700, true, true, 'inspection', 'problem_report'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000027', 'กรุณาตรวจสอบตามเอกสารมาตรฐานการตรวจสอบ', 0.0300, true, true, 'inspection', 'instruction'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000028', 'ได้แก้ไขเอกสารมาตรฐานการตรวจสอบแล้ว', 0.1000, true, true, 'inspection', 'spec_change'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000029', 'มีข้อชี้แนะจากการตรวจประเมินเกี่ยวกับบันทึกการตรวจสอบ', 0.1700, true, true, 'inspection', 'audit_finding'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000030', 'ขอให้เพิ่มพนักงานฝ่ายการตรวจสอบ', 0.2400, true, true, 'inspection', 'request'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000031', 'เกิดข้อบกพร่องในการจัดส่ง', 0.0000, true, true, 'logistics', 'problem_report'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000032', 'กรุณาตรวจสอบฉลากก่อนจัดส่ง', 0.0700, true, true, 'logistics', 'instruction'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000033', 'กำหนดส่งของการจัดส่งคือ 2026-09-30', 0.1400, true, true, 'logistics', 'schedule'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000034', 'ขอให้เพิ่มเที่ยวรถขนส่ง', 0.2100, true, true, 'logistics', 'request'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000035', 'แจ้งจำนวนการจัดส่ง', 0.2800, true, true, 'logistics', 'information'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000036', 'พบข้อบกพร่องจากการตรวจเช็คซ่อมบำรุง', 0.0400, true, true, 'maintenance', 'problem_report'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000037', 'กรุณาตรวจสอบการทำงานหลังซ่อมบำรุง', 0.1100, true, true, 'maintenance', 'instruction'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000038', 'กำหนดการซ่อมบำรุงคือวันจันทร์แรกของทุกเดือน', 0.1800, true, true, 'maintenance', 'schedule'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000039', 'กรุณาแจ้งสถานะการซ่อมบำรุง', 0.2500, true, true, 'maintenance', 'instruction'),
 ('92000000-0000-4000-8000-000000000001', '91000000-0000-4000-8000-000000000040', 'สามารถปรับเวลาจัดส่งได้หรือไม่', 0.0100, true, true, 'logistics', NULL);
SELECT genba.eval_finalize('92000000-0000-4000-8000-000000000001');
INSERT INTO genba.eval_run (id, test_set_id, run_at, model, prompt_version, note) VALUES ('92000000-0000-4000-8000-000000000002', '90000000-0000-4000-8000-000000000001', '2026-08-31 22:00', 'qwen2.5:7b-instruct-q4_K_M', 'translate.v1', 'after glossary v1 + TM bootstrap');
INSERT INTO genba.eval_result (eval_run_id, test_segment_id, mt_text, ped, glossary_ok, numbers_ok, process_pred, message_pred) VALUES
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000001', 'หลังจากเปลี่ยนเงื่อนไขการขึ้นรูป อัตราของเสียเพิ่มขึ้น', 0.0600, true, true, 'injection_molding', 'problem_report'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000002', 'กรุณาตรวจสอบอุณหภูมิแม่พิมพ์ของเครื่องขึ้นรูป', 0.1300, true, true, 'injection_molding', 'instruction'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000003', 'ได้แก้ไขเงื่อนไขแรงดันย้ำของการขึ้นรูปแล้ว', 0.2000, true, true, 'injection_molding', 'spec_change'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000004', 'ขอให้ลดเวลาการเตรียมงานของไลน์ฉีดขึ้นรูป', 0.2700, true, true, 'injection_molding', 'request'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000005', 'แจ้งสัดส่วนวัสดุรีไซเคิลของไลน์ขึ้นรูป', 0.0300, true, true, 'injection_molding', 'information'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000006', 'เกิดครีบในกระบวนการปั๊ม', 0.1000, true, true, 'press', 'problem_report'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000007', 'ให้ตรวจสอบระยะห่างแม่พิมพ์ปั๊ม', 0.1700, true, true, 'press', 'instruction'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000008', 'มีข้อชี้แนะจากการตรวจประเมินกระบวนการปั๊ม', 0.2400, true, true, 'press', 'audit_finding'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000009', 'กำหนดส่งของไลน์ปั๊มคือ 2026-10-01', 0.0000, true, true, 'press', 'schedule'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000010', 'แจ้งผลการตรวจเช็คเครื่องปั๊ม', 0.0700, true, true, 'press', 'information'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000011', 'เกิดข้อบกพร่องที่จุดการเชื่อม', 0.1400, true, true, 'welding', 'problem_report'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000012', 'กรุณาตรวจสอบกระแสการเชื่อม', 0.2100, true, true, 'welding', 'instruction'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000013', 'ได้แก้ไขเงื่อนไขการเชื่อมแล้ว', 0.2800, true, true, 'welding', 'spec_change'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000014', 'ขอให้ซ่อมจิ๊กการเชื่อม', 0.0400, true, true, 'welding', 'request'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000015', 'กำหนดการเริ่มไลน์การเชื่อมคือสัปดาห์หน้า', 0.1100, true, true, 'welding', 'schedule'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000016', 'เกิดข้อบกพร่องในกระบวนการประกอบ', 0.1800, true, true, 'assembly', 'problem_report'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000017', 'กรุณาทำตามขั้นตอนการประกอบตามเอกสารมาตรฐานการทำงาน', 0.2500, true, true, 'assembly', 'instruction'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000018', 'มีข้อชี้แนะ 3 รายการจากการตรวจประเมินกระบวนการประกอบ', 0.0100, true, true, 'assembly', 'audit_finding'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000019', 'ยืนยันกำหนดส่งของไลน์ประกอบแล้ว', 0.0800, true, true, 'assembly', 'schedule'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000020', 'เกี่ยวกับจำนวนพนักงานของไลน์ประกอบ', 0.1500, true, true, 'assembly', NULL),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000021', 'เกิดรอยขีดข่วนในกระบวนการพ่นสี', 0.2200, true, true, 'painting', 'problem_report'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000022', 'กรุณาตรวจสอบอุณหภูมิห้องพ่นสี', 0.2900, true, true, 'painting', 'instruction'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000023', 'ได้แก้ไขเงื่อนไขการพ่นสีแล้ว', 0.0500, true, true, 'painting', 'spec_change'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000024', 'ขอให้เพิ่มจิ๊กพ่นสี', 0.1200, true, true, 'painting', 'request'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000025', 'แชร์กำหนดการของไลน์พ่นสี', 0.1900, true, true, 'painting', 'schedule'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000026', 'พบของเสีย 10 ชิ้นจากการตรวจสอบ', 0.2600, true, true, 'inspection', 'problem_report'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000027', 'กรุณาตรวจสอบตามเอกสารมาตรฐานการตรวจสอบ', 0.0200, true, true, 'inspection', 'instruction'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000028', 'ได้แก้ไขเอกสารมาตรฐานการตรวจสอบแล้ว', 0.0900, true, true, 'inspection', 'spec_change'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000029', 'มีข้อชี้แนะจากการตรวจประเมินเกี่ยวกับบันทึกการตรวจสอบ', 0.1600, true, true, 'inspection', 'audit_finding'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000030', 'ขอให้เพิ่มพนักงานฝ่ายการตรวจสอบ', 0.2300, true, true, 'inspection', 'request'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000031', 'เกิดข้อบกพร่องในการจัดส่ง', 0.0000, true, true, 'logistics', 'problem_report'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000032', 'กรุณาตรวจสอบฉลากก่อนจัดส่ง', 0.0600, true, true, 'logistics', 'instruction'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000033', 'กำหนดส่งของการจัดส่งคือ 2026-09-30', 0.1300, true, true, 'logistics', 'schedule'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000034', 'ขอให้เพิ่มเที่ยวรถขนส่ง', 0.2000, true, true, 'logistics', 'request'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000035', 'แจ้งจำนวนการจัดส่ง', 0.2700, true, true, 'logistics', 'information'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000036', 'พบข้อบกพร่องจากการตรวจเช็คซ่อมบำรุง', 0.0300, true, true, 'maintenance', 'problem_report'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000037', 'กรุณาตรวจสอบการทำงานหลังซ่อมบำรุง', 0.1000, true, true, 'maintenance', 'instruction'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000038', 'กำหนดการซ่อมบำรุงคือวันจันทร์แรกของทุกเดือน', 0.1700, true, true, 'maintenance', 'schedule'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000039', 'กรุณาแจ้งสถานะการซ่อมบำรุง', 0.2400, true, true, 'maintenance', 'instruction'),
 ('92000000-0000-4000-8000-000000000002', '91000000-0000-4000-8000-000000000040', 'สามารถปรับเวลาจัดส่งได้หรือไม่', 0.0000, true, true, 'logistics', NULL);
SELECT genba.eval_finalize('92000000-0000-4000-8000-000000000002');
INSERT INTO genba.eval_run (id, test_set_id, run_at, model, prompt_version, note) VALUES ('92000000-0000-4000-8000-000000000003', '90000000-0000-4000-8000-000000000001', '2026-09-21 22:00', 'qwen2.5:7b-instruct-q4_K_M', 'translate.v2-candidate', 'prompt v2 candidate — PED regressed');
INSERT INTO genba.eval_result (eval_run_id, test_segment_id, mt_text, ped, glossary_ok, numbers_ok, process_pred, message_pred) VALUES
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000001', 'หลังจากเปลี่ยนเงื่อนไขการขึ้นรูป อัตราของเสียเพิ่มขึ้น', 0.1100, true, true, 'injection_molding', 'problem_report'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000002', 'กรุณาตรวจสอบอุณหภูมิแม่พิมพ์ของเครื่องขึ้นรูป', 0.1800, true, true, 'injection_molding', 'instruction'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000003', 'ได้แก้ไขเงื่อนไขแรงดันย้ำของการขึ้นรูปแล้ว', 0.2500, true, true, 'injection_molding', 'spec_change'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000004', 'ขอให้ลดเวลาการเตรียมงานของไลน์ฉีดขึ้นรูป', 0.3200, true, true, 'injection_molding', 'request'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000005', 'แจ้งสัดส่วนวัสดุรีไซเคิลของไลน์ขึ้นรูป', 0.0800, true, true, 'injection_molding', 'information'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000006', 'เกิดครีบในกระบวนการปั๊ม', 0.1500, true, true, 'press', 'problem_report'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000007', 'ให้ตรวจสอบระยะห่างแม่พิมพ์ปั๊ม', 0.2200, true, true, 'press', 'instruction'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000008', 'มีข้อชี้แนะจากการตรวจประเมินกระบวนการปั๊ม', 0.2900, true, true, 'press', 'audit_finding'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000009', 'กำหนดส่งของไลน์ปั๊มคือ 2026-10-01', 0.0500, true, true, 'press', 'schedule'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000010', 'แจ้งผลการตรวจเช็คเครื่องปั๊ม', 0.1200, true, true, 'press', 'information'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000011', 'เกิดข้อบกพร่องที่จุดการเชื่อม', 0.1900, true, true, 'welding', 'problem_report'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000012', 'กรุณาตรวจสอบกระแสการเชื่อม', 0.2600, true, true, 'welding', 'instruction'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000013', 'ได้แก้ไขเงื่อนไขการเชื่อมแล้ว', 0.3300, true, true, 'welding', 'spec_change'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000014', 'ขอให้ซ่อมจิ๊กการเชื่อม', 0.0900, true, true, 'welding', 'request'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000015', 'กำหนดการเริ่มไลน์การเชื่อมคือสัปดาห์หน้า', 0.1600, true, true, 'welding', 'schedule'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000016', 'เกิดข้อบกพร่องในกระบวนการประกอบ', 0.2300, true, true, 'assembly', 'problem_report'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000017', 'กรุณาทำตามขั้นตอนการประกอบตามเอกสารมาตรฐานการทำงาน', 0.3000, true, true, 'assembly', 'instruction'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000018', 'มีข้อชี้แนะ 3 รายการจากการตรวจประเมินกระบวนการประกอบ', 0.0600, true, true, 'assembly', 'audit_finding'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000019', 'ยืนยันกำหนดส่งของไลน์ประกอบแล้ว', 0.1300, true, true, 'assembly', 'schedule'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000020', 'เกี่ยวกับจำนวนพนักงานของไลน์ประกอบ', 0.2000, true, true, 'assembly', NULL),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000021', 'เกิดรอยขีดข่วนในกระบวนการพ่นสี', 0.2700, true, true, 'painting', 'problem_report'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000022', 'กรุณาตรวจสอบอุณหภูมิห้องพ่นสี', 0.3400, true, true, 'painting', 'instruction'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000023', 'ได้แก้ไขเงื่อนไขการพ่นสีแล้ว', 0.1000, true, true, 'painting', 'spec_change'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000024', 'ขอให้เพิ่มจิ๊กพ่นสี', 0.1700, true, true, 'painting', 'request'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000025', 'แชร์กำหนดการของไลน์พ่นสี', 0.2400, true, true, 'painting', 'schedule'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000026', 'พบของเสีย 10 ชิ้นจากการตรวจสอบ', 0.3100, true, true, 'inspection', 'problem_report'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000027', 'กรุณาตรวจสอบตามเอกสารมาตรฐานการตรวจสอบ', 0.0700, true, true, 'inspection', 'instruction'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000028', 'ได้แก้ไขเอกสารมาตรฐานการตรวจสอบแล้ว', 0.1400, true, true, 'inspection', 'spec_change'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000029', 'มีข้อชี้แนะจากการตรวจประเมินเกี่ยวกับบันทึกการตรวจสอบ', 0.2100, true, true, 'inspection', 'audit_finding'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000030', 'ขอให้เพิ่มพนักงานฝ่ายการตรวจสอบ', 0.2800, true, true, 'inspection', 'request'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000031', 'เกิดข้อบกพร่องในการจัดส่ง', 0.0400, true, true, 'logistics', 'problem_report'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000032', 'กรุณาตรวจสอบฉลากก่อนจัดส่ง', 0.1100, true, true, 'logistics', 'instruction'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000033', 'กำหนดส่งของการจัดส่งคือ 2026-09-30', 0.1800, true, true, 'logistics', 'schedule'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000034', 'ขอให้เพิ่มเที่ยวรถขนส่ง', 0.2500, true, true, 'logistics', 'request'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000035', 'แจ้งจำนวนการจัดส่ง', 0.3200, true, true, 'logistics', 'information'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000036', 'พบข้อบกพร่องจากการตรวจเช็คซ่อมบำรุง', 0.0800, true, true, 'maintenance', 'problem_report'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000037', 'กรุณาตรวจสอบการทำงานหลังซ่อมบำรุง', 0.1500, true, true, 'maintenance', 'instruction'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000038', 'กำหนดการซ่อมบำรุงคือวันจันทร์แรกของทุกเดือน', 0.2200, true, true, 'maintenance', 'schedule'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000039', 'กรุณาแจ้งสถานะการซ่อมบำรุง', 0.2900, true, true, 'maintenance', 'instruction'),
 ('92000000-0000-4000-8000-000000000003', '91000000-0000-4000-8000-000000000040', 'สามารถปรับเวลาจัดส่งได้หรือไม่', 0.0500, true, true, 'logistics', NULL);
SELECT genba.eval_finalize('92000000-0000-4000-8000-000000000003');

-- IF-73 exports (hash over the CSV/TMX bytes as produced by the exporter — recorded, not recomputed here)
INSERT INTO genba.export_job (id, kind, uri, row_count, sha256, created_by, created_at) VALUES ('93000000-0000-4000-8000-000000000001', 'glossary_csv', 's3://genbago-exports/glossary-2026-09-22.csv', 30, '458e83dcbe4879bf263f089206b68a25fdcf6ca56ebd767127e2088894043781', 'd0000000-0000-4000-8000-000000000003', '2026-09-22 17:20'), ('93000000-0000-4000-8000-000000000002', 'tm_tmx', 's3://genbago-exports/tm-2026-09-22.tmx', 53, 'be0a1b00a076352ace42d1562006b7e51e8812ac2bd6b705a7d05ac867244400', 'd0000000-0000-4000-8000-000000000003', '2026-09-22 17:21');
INSERT INTO audit.log (ts, user_id, action, entity, entity_id, correlation_id, detail) VALUES ('2026-09-22 17:21', 'd0000000-0000-4000-8000-000000000003', 'export.tm', 'genba.export_job', '93000000-0000-4000-8000-000000000002', 'export', '{"kind": "tm_tmx"}');

COMMIT;

-- =====================================================================
-- EXPECTED VALUES (DDS-14 §9; re-derived in Python — TEST-14 TC-005)
-- =====================================================================
\echo '=== Appendix A (J1) — the two-part rendering (AC-04, AC-08) ==='
SELECT genba.render_text((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000001' AND ordinal = 1));
\echo 'expected: SOURCE (JA) / TRANSLATION (TH) หลังจากเปลี่ยนเงื่อนไขการขึ้นรูป อัตราของเสียเพิ่มขึ้น; then a ruled INTERPRETATION (inferred — confidence 0.91) block: injection_molding / problem_report / entities {"metric": ["不良率"], "direction": "up", "parameter": ["成形条件"]} / timing "sequence stated: the change precedes the increase (causal claim implied, not verified)" / 5 checks (Melt / mould temperature … Material condition) / 4 related documents (Control plan, FMEA, Past case #178, SPC chart) / Glossary terms applied: 不良率, 成形条件'
\echo '=== J1 checks and interpretation ==='
SELECT s.status, s.tm_score, s.checks_json ->> 'clean' AS clean, i.confidence, i.ambiguous, i.process, i.message_type, i.entities_json, jsonb_array_length(i.suggested_checks_json) AS checks, jsonb_array_length(i.related_docs_json) AS docs
  FROM genba.segment s JOIN genba.interpretation i ON i.segment_id = s.id WHERE s.job_id = 'f0000000-0000-4000-8000-000000000001';
\echo 'expected: approved, tm_score NULL, clean true, 0.910, false, injection_molding, problem_report, entities as above, 5, 4'
\echo '=== AC-07: J2 exact TM reuse ==='
SELECT s.tm_score, m.method, s.mt_text = t.tgt_text AS verbatim, t.doc_ref FROM genba.segment s JOIN genba.tm_match m ON m.segment_id = s.id JOIN knowledge.tm_segment t ON t.id = m.tm_segment_id WHERE s.job_id = 'f0000000-0000-4000-8000-000000000003';
\echo 'expected: 1.000, exact, true, doc_ref job:f0000000-0000-4000-8000-000000000001#1'
\echo '=== J3 — the 8D (AC-02, AC-03, omission, fuzzy, edits) ==='
SELECT ordinal, status, (checks_json ->> 'blocked')::boolean AS blocked, (checks_json ->> 'flagged')::boolean AS flagged, edit_distance, tm_written_id IS NOT NULL AS in_tm FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' ORDER BY ordinal;
\echo 'expected: 1..11 approved (blocked false, flagged false, in_tm true), 12 needs_review; edit_distance on 3 = 0.0588, 4 = 0.1176, 5 = 0.5417'
SELECT ordinal, before_text, after_text, edit_distance FROM genba.segment_edit e JOIN genba.segment s ON s.id = e.segment_id WHERE s.job_id = 'f0000000-0000-4000-8000-000000000004' ORDER BY ordinal;
\echo 'expected: 3 edits — 3.5 mm → 3.2 mm; 修正措置 → 是正処置; one sentence → two sentences'
SELECT s.ordinal, m.method, m.score FROM genba.tm_match m JOIN genba.segment s ON s.id = m.segment_id WHERE s.job_id = 'f0000000-0000-4000-8000-000000000004' ORDER BY s.ordinal;
\echo 'expected: ordinal 6 trigram 0.921 (>= 0.85, offered with a diff, not applied)'
SELECT genba.codes_preserved('ค่าพิกัดความคลาดเคลื่อน ±0.05 mm ความหนา 3.2 mm ล็อต LOT-2609-114', '公差 ±0.05 mm、厚さ 3.2 mm、ロット LOT-2609-114') AS ac02, genba.codes_preserved('ค่าที่วัดได้ 3.2 mm เกินพิกัดความคลาดเคลื่อน', '測定値 3.5 mm が公差を超過') AS blocked_mt;
\echo 'expected: ac02 ok true source ["3.2mm","LOT-2609-114","±0.05mm"]; blocked_mt ok false missing ["3.2mm"] extra ["3.5mm"]'
SELECT genba.glossary_hits('มาตรการแก้ไข: เปลี่ยนแม่พิมพ์และตรวจสอบซ้ำ', '修正措置: 金型を交換し再検査する', 'th', 'ja') AS ac03;
\echo 'expected: applied [金型, 検査] missing [是正処置] forbidden [{term 是正処置, rendering 修正措置, mandated 是正処置}]'
\echo '=== AC-06: J4 OCR regions ==='
SELECT * FROM genba.v_ocr_flags WHERE job_id = 'f0000000-0000-4000-8000-000000000005' ORDER BY ordinal;
\echo 'expected: regions 1-3 vertical printed (0.981 / 0.972 / 0.966, low_confidence false), region 4 horizontal handwriting 0.712 low_confidence true; every region linked to a segment'
\echo '=== AC-05: J5 readings ==='
SELECT i.confidence, i.ambiguous, i.process, i.message_type, (SELECT count(*) FROM genba.reading r WHERE r.segment_id = i.segment_id) AS readings FROM genba.interpretation i JOIN genba.segment s ON s.id = i.segment_id WHERE s.job_id = 'f0000000-0000-4000-8000-000000000006';
\echo 'expected: 0.550, true, NULL, NULL, 3'
\echo '=== J6 batch progress (FR-20, NFR-07) ==='
SELECT status, files, files_done, files_failed, resumed_from_ordinal, segment_count, done_count FROM genba.v_job_progress WHERE id = 'f0000000-0000-4000-8000-000000000007';
\echo 'expected: done, 5, 5, 0, 4, 4, 4'
\echo '=== glossary versions (NFR-08) ==='
SELECT ja, version_no, effective_from, aliases FROM genba.v_glossary_current WHERE ja IN ('是正処置', '成形条件', 'キズ') ORDER BY ja;
\echo 'expected: キズ v1 2026-09-01 alias 傷 (ja); 成形条件 v1 alias 成条 (ja), สภาพการฉีด (th); 是正処置 v2 2026-10-01 alias CA (en)'
\echo '=== TM stats, consistency, candidates, usage ==='
SELECT * FROM genba.v_tm_stats ORDER BY src_lang, tgt_lang;
\echo 'expected: ja→en 11 (10 + J1E), ja→th 26 (25 + J1), th→ja 16 (5 + 11 from the 8D)'
SELECT ja, segments, consistent, inconsistent FROM genba.v_term_consistency WHERE ja IN ('不良率', '是正処置', '金型') ORDER BY ja;
SELECT ja, occurrences, status FROM genba.term_candidate ORDER BY occurrences DESC, ja;
SELECT g.ja, u.count, u.inconsistencies FROM genba.term_usage u JOIN knowledge.glossary_term g ON g.id = u.term_id WHERE u.usage_date = '2026-09-22' ORDER BY g.ja;
\echo '=== evaluation gate (AI-02, AI-05, AI-08) ==='
SELECT version, run_at, prompt_version, glossary_compliance, numbers_preserved, mean_ped, class_accuracy, passed, investigate FROM genba.v_eval_gate ORDER BY run_at;
\echo 'expected: run 1 1.0000 / 1.0000 / 0.1485 / 0.9250 passed true investigate false; run 2 1.0000 / 1.0000 / 0.1388 / 0.9250 passed true investigate false; run 3 1.0000 / 1.0000 / 0.1885 / 0.9250 passed true investigate TRUE (PED +0.04 > 2 %)'
SELECT count(*) AS rule_pred_mismatch FROM genba.eval_result x JOIN genba.test_segment t ON t.id = x.test_segment_id WHERE (SELECT c.process FROM genba.classify(t.src_text) c) IS DISTINCT FROM x.process_pred OR (SELECT c.message_type FROM genba.classify(t.src_text) c) IS DISTINCT FROM x.message_pred;
\echo 'expected: 0 (the stored predictions are the rule classifier''s own)'
\echo '=== quality dashboard (FR-31) ==='
SELECT * FROM genba.v_quality_dashboard ORDER BY day, src_lang, tgt_lang;
\echo 'expected: 2026-09-22 ja→en 1 segment, ja→th 1, th→ja 11 (mean PED over the 11 = (0.0588 + 0.1176 + 0.5417) / 11), glossary compliance 1.0000'
\echo '=== counts ==='
SELECT (SELECT count(*) FROM genba.translation_job) AS jobs, (SELECT count(*) FROM genba.segment) AS segments, (SELECT count(*) FROM genba.segment WHERE status = 'approved') AS approved,
       (SELECT count(*) FROM knowledge.tm_segment) AS tm, (SELECT count(*) FROM genba.tm_index) AS tm_index, (SELECT count(*) FROM genba.interpretation) AS interpretations,
       (SELECT count(*) FROM genba.reading) AS readings, (SELECT count(*) FROM genba.ocr_region) AS ocr_regions, (SELECT count(*) FROM genba.segment_edit) AS edits,
       (SELECT count(*) FROM genba.term_version) AS term_versions, (SELECT count(*) FROM genba.eval_result) AS eval_results;
\echo 'expected: jobs 9, segments 28, approved 13, tm 53, tm_index 53, interpretations 5, readings 3, ocr_regions 7, edits 3, term_versions 31, eval_results 120'

-- =====================================================================
-- PROBES — each must FAIL (TEST-14 TC-003). ON_ERROR_STOP is off so every probe runs.
-- =====================================================================
\set ON_ERROR_STOP off
\echo '--- P-01 approve a segment whose number changed -> SEGMENT_BLOCKED (C-02, AC-02)'
BEGIN; INSERT INTO genba.translation_job (id, kind, src_lang, tgt_lang, created_by) VALUES ('f9000000-0000-4000-8000-000000000001', 'text', 'th', 'ja', 'd0000000-0000-4000-8000-000000000001');
       SELECT genba.add_segment('f9000000-0000-4000-8000-000000000001', 1, 'ความหนา 3.2 mm', '厚さ 3.5 mm');
       SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f9000000-0000-4000-8000-000000000001'), 'd0000000-0000-4000-8000-000000000002'); ROLLBACK;
\echo '--- P-02 approve a forbidden-term segment without a reviewer note -> SEGMENT_FLAGGED (C-01, AC-03)'
BEGIN; INSERT INTO genba.translation_job (id, kind, src_lang, tgt_lang, created_by) VALUES ('f9000000-0000-4000-8000-000000000002', 'text', 'th', 'ja', 'd0000000-0000-4000-8000-000000000001');
       SELECT genba.add_segment('f9000000-0000-4000-8000-000000000002', 1, 'มาตรการแก้ไข', '修正措置');
       SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f9000000-0000-4000-8000-000000000002'), 'd0000000-0000-4000-8000-000000000002'); ROLLBACK;
\echo '--- P-03 approval by a translator -> APPROVER_ROLE (FR-30)'
BEGIN; SELECT genba.approve_segment((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 12), 'd0000000-0000-4000-8000-000000000001'); ROLLBACK;
\echo '--- P-04 interpretation with inferred = false -> INTERPRETATION_NOT_LABELLED (C-05)'
BEGIN; INSERT INTO genba.interpretation (segment_id, inferred, confidence, process, message_type) VALUES ((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000005' AND ordinal = 1), false, 0.9, 'inspection', 'information'); ROLLBACK;
\echo '--- P-05 ambiguous interpretation with one reading -> READINGS_REQUIRED (FR-15)'
BEGIN; INSERT INTO genba.reading (segment_id, ordinal, reading_ja, th, en) VALUES ((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000005' AND ordinal = 4), 1, 'x', 'x', 'x');
       INSERT INTO genba.interpretation (segment_id, confidence, ambiguous) VALUES ((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000005' AND ordinal = 4), 0.5, true); ROLLBACK;
\echo '--- P-06 related document not in the index -> RELATED_DOC_NOT_INDEXED (AI-09, AC-09)'
BEGIN; UPDATE genba.interpretation SET related_docs_json = related_docs_json || '["a0000000-0000-4000-8000-000000000999"]'::jsonb WHERE segment_id = (SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000001' AND ordinal = 1); ROLLBACK;
\echo '--- P-07 suggested check from another process -> CHECK_NOT_CURATED (FR-12)'
BEGIN; UPDATE genba.interpretation SET suggested_checks_json = '["c0000000-0000-4000-8000-000000000008"]'::jsonb WHERE segment_id = (SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000001' AND ordinal = 1); ROLLBACK;
\echo '--- P-08 glossary edit approved by a translator -> GLOSSARY_APPROVER (FR-30, NFR-08)'
BEGIN; UPDATE knowledge.glossary_term SET th = 'x', approved_by = 'd0000000-0000-4000-8000-000000000001' WHERE id = 'e0000000-0000-4000-8000-000000000004'; ROLLBACK;
\echo '--- P-09 forbidden rendering equal to the mandated one -> FORBIDDEN_IS_MANDATED'
BEGIN; UPDATE knowledge.glossary_term SET forbidden_json = '[{"lang": "ja", "text": "是正処置"}]', approved_by = 'd0000000-0000-4000-8000-000000000003' WHERE id = 'e0000000-0000-4000-8000-000000000009'; ROLLBACK;
\echo '--- P-10 confidential job on a cloud provider -> job_confidential_local (C-03)'
BEGIN; INSERT INTO genba.translation_job (kind, src_lang, tgt_lang, confidential, provider, created_by) VALUES ('text', 'ja', 'th', true, 'cloud', 'd0000000-0000-4000-8000-000000000001'); ROLLBACK;
\echo '--- P-11 editing approved memory -> TM_IMMUTABLE (FR-24)'
BEGIN; UPDATE knowledge.tm_segment SET tgt_text = 'x' WHERE id = 'b0000000-0000-4000-8000-000000000001'; ROLLBACK;
\echo '--- P-12 changing final_text without the edit function -> EDIT_CONTEXT_REQUIRED (FR-29)'
BEGIN; UPDATE genba.segment SET final_text = 'x' WHERE job_id = 'f0000000-0000-4000-8000-000000000004' AND ordinal = 12; ROLLBACK;
\echo '--- P-13 evaluation run marked passed below the gate -> EVAL_GATE (AI-02)'
BEGIN; UPDATE genba.eval_run SET mean_ped = 0.25, passed = true WHERE id = '92000000-0000-4000-8000-000000000001'; ROLLBACK;
\echo '--- P-14 TM segment approved by a translator -> TM_APPROVER (FR-24, FR-30)'
BEGIN; INSERT INTO knowledge.tm_segment (src_lang, tgt_lang, src_text, tgt_text, approver_id) VALUES ('ja', 'th', 'テスト', 'ทดสอบ', 'd0000000-0000-4000-8000-000000000001'); ROLLBACK;
\echo '--- P-15 TM segment with the same source and target language -> tm_langs_differ (platform CHECK)'
BEGIN; INSERT INTO knowledge.tm_segment (src_lang, tgt_lang, src_text, tgt_text, approver_id) VALUES ('ja', 'ja', 'テスト', 'テスト', 'd0000000-0000-4000-8000-000000000002'); ROLLBACK;
\echo '--- P-16 asserted interpretation below the ambiguity threshold -> CONFIDENCE_BELOW_THRESHOLD (FR-15)'
BEGIN; INSERT INTO genba.interpretation (segment_id, confidence, ambiguous, process, message_type) VALUES ((SELECT id FROM genba.segment WHERE job_id = 'f0000000-0000-4000-8000-000000000005' AND ordinal = 2), 0.5, false, 'inspection', 'instruction'); ROLLBACK;
\set ON_ERROR_STOP on
